backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'Aktualnosci'
    label: 'Aktualnosci'
    folder: 'src/pages/aktualnosci'
    create: true
    slug: '{{slug}}'
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data publikacji", name: "date", widget: "datetime"}
      - {label: "Opis", name: "description", widget: "text"}
      - {label: "Ujawnic posta?", name: "featuredpost", widget: "boolean"}
      - {label: "Obrazek", name: "featuredimage", widget: image}
      - {label: "Treśc calkowita", name: "body", widget: "markdown"}
      - {label: "Tagi", name: "tags", widget: "list"}
      
