backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Sciezka (np. moj-artykul , musi byc po myslnikach po to sciezka html)', name: 'path', widget: 'string'}
      - { label: 'Tytuł', name: 'title', widget: 'string' }
      - { label: 'Data publikacji', name: 'date', widget: 'datetime' }
      - { label: 'Opis pod tytułem', name: 'description', widget: 'string' }
      - { label: 'Cały opis #Kornel to gej', name: 'body', widget: 'markdown' }
