export const TOGGLE_MODE = "TOGGLE_MODE";
export const QUOTATION_TOGGLE = "QUOTATION_TOGGLE";
export const MODAL_CHOOSEN_TOGGLE = "MODAL_CHOOSEN_TOGGLE";
export const PROGRESS_BAR_SET = "PROGRESS_BAR_SET";

